# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firebase_auth_sample (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firebase_auth_sample (iOS)
  pod 'FirebaseAuth'

end

target 'firebase_auth_sample (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firebase_auth_sample (macOS)
  pod 'FirebaseAuth'

end
