# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'firebase_auth_sample (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firebase_auth_sample (iOS)
  pod 'FirebaseAuth'
  pod 'Swinject', '~> 2.7'

end

target 'firebase_auth_sample (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firebase_auth_sample (macOS)
  pod 'FirebaseAuth'
  pod 'Swinject', '~> 2.7'

end
